# Generated by Django 5.1.4 on 2024-12-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
            ),
        ),
    ]
